config/routes.rb
Rails.application.routes.draw do
  get '/blogs', to: 'blog#index', as: 'blogs'
  get '/blogs/new', to: 'blog#new', as: 'blog_new'
  get '/blogs/:id', to: 'blog#show', as: 'blog'
  post '/blogs', to: 'blog#create'
  get '/blogs/:id/edit', to: 'blog#edit', as: 'edit_blog'
  patch '/blogs/:id', to: 'blog#update'
  delete '/blogs/:id', to: 'blog#destroy', as: 'delete_blog'
  root 'blog#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, presence: true, length: { minimum: 4 }, uniqueness: true
    validates :content, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    def index
        @blogs = Blog.all
    end

    def show 
        @blog = Blog.find(params[:id])
    end

    def new
        @blog = Blog.new
    end

    def create
        @blog = Blog.create(blog_params)
        if @blog.save
            redirect_to blogs_path
        else
            render :new
        end
    end
  
    def edit
        @blog = Blog.find(params[:id])
    end

    def update
        @blog = Blog.find(params[:id])
         @blog.update(blog_params)
         if @blog.valid?
         redirect_to blog_path(@blog)
        
        end
    end
    
    def destroy
        @blog = Blog.find(params[:id])
        @blog.destroy
        redirect_to blogs_path
    end

  
    private
    def blog_params
        params.require(:blog).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/_form.html.erb
<%= form_with(model: @blog, remote: true) do |form| %>
    <%= form.label :title, 'Enter a title'%>
    <br />
    <%= form.text_field :title %>
  <br />
  <br />
    <%= form.label :content, 'Enter your blog'%>
    <br />
    <%= form.text_area :content, size:"60x10"%>
  <br />
  <br />
    <%= form.submit 'Create Blog Post' %>
  <% end %>
  

app/views/blog/edit.html.erb
<h1> Edit Blog Post </h1>

<div class = post-container>
<%= form_with(model: @blog, remote: true) do |form| %>
    <%= form.label :title, 'Enter a title for your blog'%>
    <br />
    <%= form.text_field :title %>
  <br />
  <br />
    <%= form.label :content, 'Enter your blog'%>
    <br />
    <%= form.text_area :content,size:"60x10" %>
  <br />
  <br />
    <%= form.submit 'Update Blog Post' %>
  <% end %>
</div>

  <%= link_to 'Back', blogs_path %>
    

   

app/views/blog/index.html.erb
<h1>All Blogs Here</h1>


<% if @blogs.any? %>
  <div class="card-container">
    <% @blogs.each do |blog| %>
      <div class="card">
        <h3><%= link_to blog.title, blog_path(blog) %></h3>
        <p class="content"><%= blog.content %></p>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No blog posts available.</p>
<% end %>


<div class = "create">
<p><%= link_to 'Create a new blog post', blog_new_path %></p>
</div>

app/views/blog/new.html.erb
<h1>Add a new blog post</h1>
<div class = post-container>
<%= render partial: 'form', locals: {blog: @blog} %>
</div>
<%= link_to 'Back', blogs_path %>

app/views/blog/show.html.erb
<h1>Blog posts</h1>


<p class = "show"><%= @blog.title %></p>
<div class = "content-card">
<p><%= @blog.content %></p>
</div>

<div class = "links">
<p><%= link_to 'Home', blogs_path %> </p>
<br />
<p><%= link_to 'edit post', edit_blog_path(@blog) %></p>
<br />
<p><%= link_to 'delete post', delete_blog_path(@blog), data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete #{@blog.title}?"} %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFullStack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>